---
- name: Install mysql
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-mysqldb

- name: Create Mysql configuration bak
  command: cp /etc/mysql/my.cnf /etc/mysql/my.bak.cnf creates=/etc/mysql/my.bak.cnf

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes

- name: Create Application Database
  mysql_db: name={{ db_name }} state=present

- name: Create Application DB User
  mysql_user: name={{ db_user }} password={{ db_password }} priv=*.*:ALL,GRANT host='192.168.33.11' state=present