---
- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: Install php-fpm and deps
  sudo: true
  apt: name={{ item }} state=present
  with_items:
    - php5.6-fpm

- name: Copy nginx backup
  command: cp /etc/php/5.6/fpm/php.ini /etc/php/5.6/fpm/php.bak.ini creates=/etc/php/5.6/fpm/php.bak.ini   

- name: php.ini configuration
  sudo: yes
  template: src=php.ini dest=/etc/php/5.6/fpm/php.ini
  notify: restart php5.6-fpm



# Composer

# - stat: path=/usr/local/bin/composer
#   register: composer_folder

# - name: PHP | Install Composer
#   shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
#   when: composer_folder.stat.isdir is not defined