---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx backup
  command: cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak creates=/etc/nginx/sites-available/default.bak

- name: Copy nginx configuration
  sudo: yes
  template: src=default.conf dest=/etc/nginx/sites-available/default
  notify: restart nginx

# - name: Create vhost Directory
#   sudo: yes
#   command: mkdir /etc/nginx/vhost

- name: Copy nginx configuration vhost
  sudo: yes
  template: src=project1.conf dest=/etc/nginx/sites-enabled/project1.conf
  notify: restart nginx

- name: Copy nginx configuration vhost
  sudo: yes
  template: src=project2.conf dest=/etc/nginx/sites-enabled/project2.conf
  notify: restart nginx

- name: Copy nginx configuration vhost
  sudo: yes
  template: src=project3.conf dest=/etc/nginx/sites-enabled/project3.conf
  notify: restart nginx
